<#
.SYNOPSIS
# ver 0.99 (ve1) Email parsing from univis.uni-bamberg.de

.DESCRIPTION
===================================================================================================
This script processes profile URLs from a CSV file (generated by Dep.ps1) to extract full names and 
associated email addresses. It includes a validation filter that excludes generic or technical 
email addresses where the name and address do not match, ensuring high data accuracy
===================================================================================================

*Note: This script is designed to process public directory pages. 
Please ensure you have the appropriate permissions to access the target website.*

.EXAMPLE 
    ./start.ps1 -input_csv Filename.csv
    This run script and import CSV table from Filename.csv
    Default import CSV: All_Departments_BFS.csv

.PARAMETER input_csv
    Path to CSV filename for input (default All_Departments_BFS.csv)
#>

param (
    [string]$input_csv,
    [switch]$ver,
    [switch]$help
    )

    # 1. Version (-ver)
if ($ver) {
    Write-Host "Script version: 0.99"
    exit # stop script here
}

if ($help) {
    Get-Help $PSCommandPath
    exit # stop script here
}

# 3. variable filename
if ($input_csv) {
    $filename = $input_csv
    Write-Host "Input from filename.csv: $filename"
} else {
    Write-Host "Parameter -input no used. Using default input All_Departments_BFS.csv "
}

if (-not $input_csv) {
    $input_csv = "All_Departments_BFS.csv"
}

#Start
Write-Host "Script started..." -ForegroundColor Green


function Convert-NameToAscii {
    param([string]$s)

    $normalized = $s.Normalize([Text.NormalizationForm]::FormD)

    $sb = New-Object System.Text.StringBuilder

    foreach ($c in $normalized.ToCharArray()) {

        $category = [Globalization.CharUnicodeInfo]::GetUnicodeCategory($c)

        if ($category -eq [Globalization.UnicodeCategory]::NonSpacingMark) {
            # üäö
            [void]$sb.Append("e")
        }
        else {
            [void]$sb.Append($c)
        }
    }

    $result = $sb.ToString().ToLower()

    # ß
    $result = $result -replace 'ß','ss'

    return $result
}


# URL to scrape - please update this variable before running
#$baseUrl = "https://INSERT_TARGET_URL_HERE"


# CSVfile
#$deptLinks = Import-Csv ".\All_Departments_BFS.csv"
$deptLinks = Import-Csv "$input_csv"


$results = @()
$noEmailResults = @()
$TotalEmployees = 0
$TotalNoEmail = 0

foreach ($dept in $deptLinks) {
    Write-Host "Processing: $($dept.Dept)" -ForegroundColor Cyan

    try {
        $page = Invoke-WebRequest -Uri $dept.URL
        $html = $page.Content

        $contactRows = [regex]::Matches($html, '<tr>(.*?)</tr>', 'Singleline')

        $currentName = ""
        $currentEmails = @()

        foreach ($row in $contactRows) {
            $rowHtml = $row.Groups[1].Value

            $nameMatch = [regex]::Match($rowHtml, '<a\s+href="form\?dsc=anew/tel_view[^"]+">([^<]+)</a>')
            if ($nameMatch.Success) {
                if ($currentName -ne "") {
                    $nameParts = $currentName.Split(",") | ForEach-Object { Convert-NameToAscii($_.Trim()) }
                    $matchedEmail = $currentEmails | Where-Object { 
                        $emailLower = $_.ToLower()
                        $nameParts[1] -and $nameParts[0] -and $emailLower.Contains($nameParts[1]) -and $emailLower.Contains($nameParts[0])
                    } | Select-Object -First 1

                    $TotalEmployees++
                    if (-not $matchedEmail) { $TotalNoEmail++ }

                    $outputColor = if ($matchedEmail) { "White" } else { "DarkYellow" }

                    # Orange colour string
                    Write-Host "Employer: $currentName | Normalized: $($nameParts -join ', ') | Emails: $($currentEmails -join ', ') | Selected: $matchedEmail" -ForegroundColor $outputColor

                    $results += [PSCustomObject]@{
                        Department = $dept.Dept
                        Name       = $currentName
                        Email      = $matchedEmail
                    }

                    if (-not $matchedEmail) {
                        $noEmailResults += [PSCustomObject]@{
                            Department = $dept.Dept
                            Name       = $currentName
                        }
                    }
                }

                # new employer
                $currentName = $nameMatch.Groups[1].Value.Trim()
                $currentEmails = @()

                $emailMatches = [regex]::Matches($rowHtml, '<a\s+href="mailto:([^"]+)">')
                foreach ($m in $emailMatches) { $currentEmails += $m.Groups[1].Value.Trim() }
            } else {
                # extra row with email
                $emailMatches = [regex]::Matches($rowHtml, '<a\s+href="mailto:([^"]+)">')
                foreach ($m in $emailMatches) { $currentEmails += $m.Groups[1].Value.Trim() }
            }
        }

        # last record
        if ($currentName -ne "") {
            $nameParts = $currentName.Split(",") | ForEach-Object { Convert-NameToAscii($_.Trim()) }
            $matchedEmail = $currentEmails | Where-Object { 
                $emailLower = $_.ToLower()
                $nameParts[1] -and $nameParts[0] -and $emailLower.Contains($nameParts[1]) -and $emailLower.Contains($nameParts[0])
            } | Select-Object -First 1

            $TotalEmployees++
            if (-not $matchedEmail) { $TotalNoEmail++ }

            $outputColor = if ($matchedEmail) { "White" } else { "DarkYellow" }

            Write-Host "Employer: $currentName | Normalized: $($nameParts -join ', ') | Emails: $($currentEmails -join ', ') | Selected: $matchedEmail" -ForegroundColor $outputColor

            $results += [PSCustomObject]@{
                Department = $dept.Dept
                Name       = $currentName
                Email      = $matchedEmail
            }

            if (-not $matchedEmail) {
                $noEmailResults += [PSCustomObject]@{
                    Department = $dept.Dept
                    Name       = $currentName
                }
            }
        }

    } catch {
        Write-Warning "Unable to process $($dept.URL): $_"
    }
}


$results | Format-Table -AutoSize

# export CSV
$results | Export-Csv ".\All_Contacts.csv" -NoTypeInformation -Encoding UTF8
$noEmailResults | Export-Csv ".\NoEmail_Contacts.csv" -NoTypeInformation -Encoding UTF8

# statistic
$percentNoEmail = if ($TotalEmployees -gt 0) { [math]::Round(($TotalNoEmail / $TotalEmployees) * 100, 2) } else { 0 }

Write-Host "===============================================" -ForegroundColor Cyan
Write-Host "University Summary:" -ForegroundColor Cyan
Write-Host "Total Employees: $TotalEmployees"
Write-Host "Employees without email: $TotalNoEmail"
Write-Host "Percentage without email: $percentNoEmail %"
Write-Host "===============================================" -ForegroundColor Cyan

Write-Host "Finished. All_Contacts.csv and NoEmail_Contacts.csv created." -ForegroundColor Green
